### ISSUE TITLE
Add support for MemberPress

### ISSUE THREAD

**Issue by gspice** [awesomemotive/affiliatewp-order-details-for-affiliates#39]
Customer integrating with MemberPress would like to show order information about the customer for referrals in the affiliate area:

https://secure.helpscout.net/conversation/451171809/68722?folderId=205529

**Comment by gspice** [comment]
https://secure.helpscout.net/conversation/534822038/77440?folderId=1170842

**Comment by gspice** [comment]
Another request to add support for MemberPress:

https://secure.helpscout.net/conversation/645883072/88334/?folderId=205529

**Comment by gspice** [comment]
Another request:
https://secure.helpscout.net/conversation/650915196/88765?folderId=205529

**Comment by gspice** [comment]
Request to support MemberPress : 
https://secure.helpscout.net/conversation/985374935/134779?folderId=205524

>want to show affiliate the name or email of who signed up
can I show the affiliate (in their dashboard or in their "new referral" email) any info on the customer who signed up?

**Comment by gspice** [comment]
Requested in HS:
https://secure.helpscout.net/conversation/1043935630/141075/

>Order Details For Affiliates For Memberpress
Hey guys, are there any plans on a MemberPress integration for this plugin in the works?

**Comment by tjackson1317** [comment]
Another request:

https://secure.helpscout.net/conversation/1322908098/169103?folderId=3962735

**Comment by gspice** [comment]
Same guy as above wanting to know when MemberPress can be added:

>I also updated the plugin in hope that you had added support for memberpress for this plugin :) Surely it wouldn't be that difficult to mimic the functionality but just traverse the Memberpress data from the subscription id rather than the WooCommerce one? Do you have any plans for adding this?

**Comment by tjackson1317** [comment]
> My affiliates are not able to see any names attached to memberships they are selling. There is no names included in the email notification and the only thing we are seeing are number references in the dashboard area? It seems like the customer's name should be included by default for the software? This will make for difficult tracking? Any help or setting adjustments that I can make?

https://secure.helpscout.net/conversation/1511394426/184796?folderId=205524

**Comment by gspice** [comment]
I located all of these HS links and emails in the AM HS account and have added the feature request to the new site:

https://team.affiliatewp.com/feature-requests/add-support-for-memberpress/

Closing this now.
